#!/bin/sh
set -e

. /usr/share/debconf/confmodule

case "$1" in
  install)
    if [ -z "${DEBCONF_RECONFIGURE}" ]; then
      db_get "dokku/key_file"
      if [ ! -f "$RET" ]; then
          echo "Error: keyfile '$RET' not found."
          echo "       you can enter a new keyfile path when you restart the installation."
          db_reset "dokku/key_file"
          exit 1
      fi
    fi
    ;;

  upgrade)
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
